### ISSUE TITLE
Customer: Home Page Teaser Story

### ISSUE THREAD

**Issue by Hoffit** [My-Dog-Spot/happy-puppy#47]
We need to refactor the home page to not step on our source of inspiration: Idaho Scotties. We've not gotten any permission from them. So - we should adjust some of our language and content accordingly. For example, '....Idaho Scotties...' should be updated. One thought....change it to 'The Code Fellows House of Scotties'.

**Comment by MthwBrwn** [comment]
That's a good thought . I'll adjust the Home page
